image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - test

test:
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml up --build -d
    - docker-compose -f docker-compose.ci.yml run consensus npm run test-all
    - docker-compose -f docker-compose.ci.yml down
