version: '3.2'
services:
  consensus:
    build: .
    command: sh -c "npm run up"
  api:
    build:
      context: ../consensus-api
      dockerfile: Dockerfile
    ports:
      - '4567:4567'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/db
    env_file:
      - password_mail.env
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      - AUTH=no
    ports:
      - 27017:27017
