version: '3'
services:
  consensus:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - '.:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'


  selenium:
    image: selenium/standalone-chrome
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
    ports:
      - 4444:4444

  e2e:
    build:
      context: .
      dockerfile: e2e.docker
    volumes:
      - '.:/test'
    depends_on:
      - consensus
      - selenium
      - system
    command: sh -c 'npm install && npm run build'

  system:
    build:
      context: ./system
    volumes:
      - './system:/system'
    command: rackup --port 4567 -o 0.0.0.0
    ports:
      - 4567:4567

volumes:
  bundle:
    driver: local
