version: '3.2'
services:

  consensus:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: .
        target: /opt/consensus

  api:
    image: registry.gitlab.com/devscola/consensus-api:v0.1
    ports:
      - '4567:4567'

  selenium:
    image: selenium/standalone-chrome:3.8.1
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
