version: '3.2'
services:
  consensus:
    build: .
    command: sh -c "npm run up"

  selenium:
    image: selenium/standalone-chrome:3.8.1
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
