version: '2.0'
services:
  nginx_app:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - './public/.:/usr/share/nginx/html'
      - './conf/nginx.conf:/etc/nginx/nginx.conf'

  consensus:
    build: .
    volumes:
      - '.:/consensus/app'
    depends_on:
      - nginx_app

  selenium:
    image: selenium/standalone-chrome:3.8.1
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
    ports:
      - '4444:4444'

volumes:
  vol_app:
    driver: local
