version: '3.2'
services:

  consensus:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./public/
        target: /opt/consensus_applicative/public/
      - type: bind
        source: ./src/
        target: /opt/consensus_applicative/src/
      - type: bind
        source: ./conf/
        target: /opt/consensus_applicative/conf/
      - type: bind
        source: ./test/
        target: /opt/consensus_applicative/test/
      - type: bind
        source: ./package.json
        target: /opt/consensus_applicative/package.json

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '4567:4567'

  selenium:
    image: selenium/standalone-chrome:3.8.1
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
