version: '2'
services:
  api:
    image: registry.gitlab.com/devscola/consensus-api:v0.1
    ports:
      - '4567:4567'

  consensus:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - '.:/usr/share/nginx/html'
      - './conf/nginx.conf:/etc/nginx/nginx.conf'

  selenium:
    image: selenium/standalone-chrome
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
    ports:
      - '4444:4444'

  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    working_dir: '/test'
    volumes:
      - '.:/test'
    depends_on:
      - consensus
      - selenium
    command: sh -c 'npm install && npm run build-watch -s'

volumes:
  bundle:
    driver: local
