source "https://rubygems.org"
ruby '>= 2.4.2'

gem 'sinatra', '~> 2.0.0'
gem 'rake', '~> 12.3.0'
gem 'mail'

group :development do
  gem 'rerun', '~> 0.11.0'
end

group :test do
  gem 'rspec', '~> 3.7.0'
end
