# frozen_string_literal: true

source "https://rubygems.org"
ruby '2.4.2'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", '~> 2.0.0'
gem "shotgun"

group :test do
  gem 'rspec', '~> 3.7.0'
end
